import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.7.1";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const body = await req.json();
    const { blogPostId, title, intro, category, emotional_hook, target_audience, unique_angle } = body;

    let postTitle = title;
    let postIntro = intro;
    let postCategory = category;

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    if (blogPostId && !postTitle) {
      const { data: post, error: fetchError } = await supabase
        .from('blog_posts')
        .select('title, intro, category')
        .eq('id', blogPostId)
        .single();

      if (fetchError || !post) {
        throw new Error(`Failed to fetch blog post: ${fetchError?.message}`);
      }
      postTitle = post.title;
      postIntro = post.intro;
      postCategory = post.category;
    }

    if (!postTitle) {
      throw new Error('Either blogPostId or title is required');
    }

    console.log('Generating image for:', postTitle);

    // Load prompt template and model from ai_prompts table
    let imagePromptTemplate = `Professional, high-quality featured image for a blog article about "{title}". 
    Context: {intro}
    Style: Modern, clean, professional illustration suitable for a real estate investment blog.
    Category: {category}
    Requirements: 16:9 aspect ratio, Mediterranean colors (blue, white, terracotta), no text overlay, ultra high resolution.`;
    let imageModel = 'google/gemini-3-pro-image-preview';

    try {
      const { data: promptConfig } = await supabase
        .from('ai_prompts')
        .select('prompt_text, model_id')
        .eq('prompt_key', 'blog_image')
        .maybeSingle();

      if (promptConfig?.prompt_text) {
        imagePromptTemplate = promptConfig.prompt_text;
      }
      if (promptConfig?.model_id) {
        imageModel = promptConfig.model_id;
      }
    } catch (e) {
      console.warn('Could not load image prompt config, using defaults:', e);
    }

    // Replace placeholders — including enriched briefing fields
    const imagePrompt = imagePromptTemplate
      .replace(/\{title\}/g, postTitle)
      .replace(/\{intro\}/g, (postIntro || '').substring(0, 200))
      .replace(/\{category\}/g, postCategory || 'General')
      .replace(/\{emotional_hook\}/g, emotional_hook || '')
      .replace(/\{target_audience\}/g, target_audience || '')
      .replace(/\{unique_angle\}/g, unique_angle || '');

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY not configured');
    }

    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: imageModel,
        messages: [{ role: 'user', content: imagePrompt }],
        modalities: ['image', 'text']
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error('AI Gateway error:', aiResponse.status, errorText);
      if (aiResponse.status === 429) {
        return new Response(JSON.stringify({ error: 'Rate limit bereikt. Probeer het over een minuut opnieuw.', success: false }), {
          status: 429, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }
      if (aiResponse.status === 402) {
        return new Response(JSON.stringify({ error: 'AI-tegoed onvoldoende. Vul je credits aan in Settings → Workspace → Usage.', success: false }), {
          status: 402, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }
      throw new Error(`AI image generation failed: ${errorText}`);
    }

    const aiData = await aiResponse.json();
    const imageBase64 = aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;
    if (!imageBase64) {
      throw new Error('No image generated by AI');
    }

    const base64Data = imageBase64.split(',')[1];
    const imageBuffer = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));

    const fileName = `blog-${blogPostId || Date.now()}-${Date.now()}.png`;
    const { error: uploadError } = await supabase.storage
      .from('blog-images')
      .upload(fileName, imageBuffer, { contentType: 'image/png', upsert: true });

    if (uploadError) {
      throw new Error(`Failed to upload image: ${uploadError.message}`);
    }

    const { data: { publicUrl } } = supabase.storage
      .from('blog-images')
      .getPublicUrl(fileName);

    if (blogPostId) {
      const { error: updateError } = await supabase
        .from('blog_posts')
        .update({ featured_image: publicUrl })
        .eq('id', blogPostId);

      if (updateError) {
        throw new Error(`Failed to update blog post: ${updateError.message}`);
      }
    }

    return new Response(
      JSON.stringify({ success: true, imageUrl: publicUrl, message: 'Blog image generated successfully' }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 200 }
    );

  } catch (error) {
    console.error('Error in generate-blog-image:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
    return new Response(
      JSON.stringify({ error: errorMessage, success: false }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
    );
  }
});
